### ISSUE TITLE
Cannot build in Ubuntu 18.04.1

### ISSUE THREAD

**Issue by jtsdana** [InteractiveComputerGraphics/SPlisHSPlasH#41]
Steps to reproduce:

1. git clone version 2.3.0
2. cmake .
3. make 

I would assume it has something to do with OpenMP but i just cannot seem to figure out where the error happens.
The output of make is:
```
[ 85%] Building CXX object Simulators/DynamicBoundarySimulator/CMakeFiles/DynamicBoundarySimulator.dir/main.cpp.o
<command-line>:0:0: warning: "PBD_DATA_PATH" redefined
<command-line>:0:0: note: this is the location of the previous definition
In file included from /usr/include/c++/7/parallel/algorithmfwd.h:34:0,
                 from /usr/include/c++/7/parallel/algorithm:35,
                 from /home/john/fluid_sim/SPlisHSPlasH/extern/install/CompactNSearch/include/Config.h:18,
                 from /home/john/fluid_sim/SPlisHSPlasH/extern/install/CompactNSearch/include/CompactNSearch.h:3,
                 from /home/john/fluid_sim/SPlisHSPlasH/SPlisHSPlasH/Simulation.h:8,
                 from /home/john/fluid_sim/SPlisHSPlasH/Simulators/DynamicBoundarySimulator/main.cpp:19:
/usr/include/c++/7/parallel/tags.h: In member function ‘__gnu_parallel::_ThreadIndex __gnu_parallel::parallel_tag::__get_num_threads()’:
/usr/include/c++/7/parallel/tags.h:66:18: error: ‘omp_get_max_threads’ was not declared in this scope
           return omp_get_max_threads();
                  ^~~~~~~~~~~~~~~~~~~
/usr/include/c++/7/parallel/tags.h:66:18: note: suggested alternative:
In file included from /home/john/fluid_sim/SPlisHSPlasH/extern/install/PositionBasedDynamics/include/Simulation/kdTree.inl:4:0,
                 from /home/john/fluid_sim/SPlisHSPlasH/extern/install/PositionBasedDynamics/include/Simulation/kdTree.h:95,
                 from /home/john/fluid_sim/SPlisHSPlasH/extern/install/PositionBasedDynamics/include/Simulation/BoundingSphereHierarchy.h:6,
                 from /home/john/fluid_sim/SPlisHSPlasH/extern/install/PositionBasedDynamics/include/Simulation/DistanceFieldCollisionDetection.h:7,
                 from /home/john/fluid_sim/SPlisHSPlasH/extern/install/PositionBasedDynamics/include/Simulation/CubicSDFCollisionDetection.h:5,
                 from /home/john/fluid_sim/SPlisHSPlasH/Simulators/DynamicBoundarySimulator/PositionBasedDynamicsWrapper/PBDWrapper.h:10,
                 from /home/john/fluid_sim/SPlisHSPlasH/Simulators/DynamicBoundarySimulator/main.cpp:13:
/usr/lib/gcc/x86_64-linux-gnu/7/include/omp.h:88:12: note:   ‘PBD::omp_get_max_threads’
 extern int omp_get_max_threads (void) __GOMP_NOTHROW;
```

```
 gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/7/lto-wrapper
OFFLOAD_TARGET_NAMES=nvptx-none
OFFLOAD_TARGET_DEFAULT=1
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 7.4.0-1ubuntu1~18.04.1' --with-bugurl=file:///usr/share/doc/gcc-7/README.Bugs --enable-languages=c,ada,c++,go,brig,d,fortran,objc,obj-c++ --prefix=/usr --with-gcc-major-version-only --program-suffix=-7 --program-prefix=x86_64-linux-gnu- --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-libmpx --enable-plugin --enable-default-pie --with-system-zlib --with-target-system-zlib --enable-objc-gc=auto --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-offload-targets=nvptx-none --without-cuda-driver --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 7.4.0 (Ubuntu 7.4.0-1ubuntu1~18.04.1) 
```

**Comment by ManosAgelidis** [comment]
Hi, this basically means that openMP is not found properly by cmake. Could you add these lines somewhere in the CMakeLists.txt in Simulators/DynamicBoundarySimulator and Simulators/StaticBoundarySimulator

OPTION (USE_OpenMP "Use OpenMP" ON)
IF(USE_OpenMP)
FIND_PACKAGE(OpenMP)
IF(OPENMP_FOUND)
SET(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} ${OpenMP_C_FLAGS}")
SET(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} ${OpenMP_CXX_FLAGS}")
ENDIF()
ENDIF()

**Comment by janbender** [comment]
We will add this in the next version.

**Comment by janbender** [comment]
This was added in the last version. Did you test it again?

**Comment by jtsdana** [comment]
> This was added in the last version. Did you test it again?

I just tested, it now builds without problems :)
